steps:
  - name: "hashicorp/terraform"
    id: terraform-apply
    dir: infra/deployment/terraform/apps
    script: |
      terraform init -backend-config=bucket=$TFSTATE_BUCKET

      terraform apply --auto-approve
    env:
      - "TFSTATE_BUCKET=${_TFSTATE_BUCKET}"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_doc_ai_location=${_DOC_AI_LOCATION}"
      - "TF_VAR_dw_ui_service_account_email=${_DW_UI_SERVICE_ACCOUNT_EMAIL}"
      - "TF_VAR_dw_ui_service_account_private_key=${_DW_UI_SERVICE_ACCOUNT_PRIVATE_KEY}"
      - "TF_VAR_schema_id=${_SCHEMA_ID}"
      - "TF_VAR_admins_group_email=${_ADMINS_GROUP_EMAIL}"
      - "TF_VAR_users_group_email=${_USERS_GROUP_EMAIL}"
      - "TF_VAR_alerting_emails=${_ALERTING_EMAILS}"
      - "TF_VAR_sourcerepo_name=${_SOURCEREPO_NAME}"
      - "TF_VAR_branch_name=${_BRANCH_NAME}"
      - "TF_VAR_ocr_processor_name=${_OCR_PROCESSOR_NAME}"
      - "TF_VAR_cde_lrs_type_processor_name=${_CDE_LRS_TYPE_PROCESSOR_NAME}"
      - "TF_VAR_cde_general_type_processor_name=${_CDE_GENERAL_TYPE_PROCESSOR_NAME}"
      - "TF_VAR_cde_classifier_type_processor_name=${_CDE_CLASSIFIER_TYPE_PROCESSOR_NAME}"
